name: Example Runs

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  BLITZAR_BACKEND: cpu

jobs:
  example-tests:
    name: Run Example Commands
    runs-on: large-8-core-32gb-22-04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        run: curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env

      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=non-interactive
          sudo apt-get update
          sudo apt-get install -y clang lld

      # Runs the examples 
      - name: Run hello_world example (With Blitzar)
        run: cargo run --example hello_world --features="test"
      - name: Run hello_world example (Without Blitzar and With Rayon)
        run: cargo run --example hello_world --no-default-features --features="rayon test"
      - name: Run hello_world example (Without Blitzar and Without Rayon)
        run: cargo run --example hello_world --no-default-features --features="test"
      - name: Run space example
        run: cargo run --example space
      - name: Run dog breeds example
        run: cargo run --example dog_breeds
      - name: Run wood types example
        run: cargo run --example wood_types
      - name: Run dinosaurs example
        run: cargo run --example dinosaurs
      - name: Run books example
        run: cargo run --example books
      - name: Run brands example
        run: cargo run --example brands
      - name: Run avocado-prices example
        run: cargo run --example avocado-prices
      - name: Run plastics example
        run: cargo run --example plastics
      - name: Run sushi example
        run: cargo run --example sushi
      - name: Run countries example
        run: cargo run --example countries
      - name: Run rockets example
        run: cargo run --example rockets
      - name: Run posql_db example (With Blitzar)
        run: bash crates/proof-of-sql/examples/posql_db/run_example.sh
      - name: Run posql_db example (Without Blitzar)
        run: bash crates/proof-of-sql/examples/posql_db/run_example.sh --no-default-features --features="rayon"
